### ISSUE TITLE
Bug al redimensionar el reproductor

### ISSUE THREAD

**Issue by vlanknotblank** [midudev/la-velada-web-oficial#401]
# Comportamiento esperado

Al redimensionar el reproductor, con el video cargado, no debería verse la imagen de fondo al redimensionarlo.

# Comportamiento actual

Al reproducir el video, y cambiar el ancho de la página, se puede observar que se sigue visualizando el thumbnail

![ezgif-5-091b36e6fa](https://github.com/midudev/la-velada-web-oficial/assets/61855340/9ef4fb3b-1bb1-445c-a82c-d056f25d33aa)

# Información del bug (si corresponde)
Debería ocultarse la imagen de fondo al hacer click
```css
/* Post-click styles */
lite-youtube.lyt-activated {
  cursor: unset;
  background-image: unset !important;
}
```
## Pasos para reproducirlo
1. Reproducir el video
2. Redimensionar el navegador

## Contexto
- Navegador: Firefox
- Versión del navegador: 123.0-1
- Sistema operativo: Linux
